mode = "TGM3Master"

[game]
gravity = 20.0
are = 10
line_are = 6
das = 8
lock_delay = 18
line_clear_delay = 6

# http://sdl2referencejp.osdn.jp/SDLKeycodeLookup.html
[key]
left = 97
right = 100
soft_drop = 115
hard_drop = 119
cw = 107
ccw = 106
hold = 32
restart = 114
